---
title: "Data Cleaning PT1"
output: html_document
date: "2026-07-14"
---
```{r}
ufo <- read_csv("https://sisbid.github.io/Data-Wrangling/data/ufo/ufo_data_complete.csv")
ufo
```
```{r}
p <- problems(ufo)
problems(ufo) %>% count(expected, actual, col)
```


```{r}
head(ufo)

```


```{r}
slice(ufo, 30389 -1) %>% glimpse()
```


```{r}
url <- "https://sisbid.github.io/Data-Wrangling/data/ufo/ufo_data_complete.csv"
ufo <- read_csv(url, col_types = cols(`duration (seconds)` = "c"))
```


```{r}
head(ufo, n = 2)
```


```{r}
p %>% pull(row)
```


```{r}
library(janitor)
library(dplyr)
colnames(ufo)
ufo_clean <- ufo %>% clean_names()
ufo_clean

```


```{r}
ufo_clean %>% 
  mutate(country = 
           case_when(country == "gb" ~ "Great Britain",
                     country == "us" ~ "United States",
                     country == "ca" ~ "Canada",
                     country == "DE" ~ "Germany"), 
         .default = country) %>%
  glimpse()
```


```{r}
ufo_clean %>% 
  mutate(region = 
           case_when(country == "gb" ~ "Europe",
                     country == "us" ~ "North America",
                     country == "ca" ~ "North America",
                     country == "DE" ~ "Europe"), 
         .default = "Other") %>%
  glimpse()
```


```{r}
ufo_clean %>% 
  filter(str_detect(
    string = duration_seconds, pattern = "`")
  )
```


```{r}
ufo_clean <- ufo_clean %>%
  mutate(duration_seconds = as.numeric(duration_seconds))

```


```{r}
ufo_clean %>% pull(comments) %>%
  str_subset("two alients")
```


```{r}
ufo_clean %>% pull(comments) %>%
  str_subset("two alients")
```
```{r}
pull(ufo_clean, duration_hours_min)
```
```{r}
ufo_clean %>% seperate(datetime, )
```

